name:                internet-archive-crawler
version:             0.1.0.0
homepage:            https://github.com/dzhus/internet-archive-crawler#readme
license:             BSD3
author:              Dmitry Dzhus
maintainer:          dima@dzhus.org
copyright:           2018 Dmitry Dzhus
category:            Web
extra-source-files:
- README.md

default-extensions:
  - DeriveGeneric
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies

dependencies:
  - base < 5
  - aeson
  - classy-prelude
  - html-conduit
  - http-client
  - http-client-tls
  - http-conduit
  - lens
  - pandoc
  - retry
  - text
  - xml-conduit

executables:
  internet-archive-crawler:
    source-dirs:      src
    main:             Main.hs
